package com.example.kafkastarter.model;

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AnimeAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5873865364605489200L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnimeAvro\",\"fields\":[{\"name\":\"title\",\"type\":\"string\",\"doc\":\"Title of the Anime\"},{\"name\":\"releaseYear\",\"type\":\"long\",\"doc\":\"Release Year of Anime\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AnimeAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AnimeAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AnimeAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AnimeAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AnimeAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AnimeAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AnimeAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AnimeAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AnimeAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Title of the Anime */
  private java.lang.CharSequence title;
  /** Release Year of Anime */
  private long releaseYear;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AnimeAvro() {}

  /**
   * All-args constructor.
   * @param title Title of the Anime
   * @param releaseYear Release Year of Anime
   */
  public AnimeAvro(java.lang.CharSequence title, java.lang.Long releaseYear) {
    this.title = title;
    this.releaseYear = releaseYear;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return title;
    case 1: return releaseYear;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: title = (java.lang.CharSequence)value$; break;
    case 1: releaseYear = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'title' field.
   * @return Title of the Anime
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * Title of the Anime
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'releaseYear' field.
   * @return Release Year of Anime
   */
  public long getReleaseYear() {
    return releaseYear;
  }


  /**
   * Sets the value of the 'releaseYear' field.
   * Release Year of Anime
   * @param value the value to set.
   */
  public void setReleaseYear(long value) {
    this.releaseYear = value;
  }

  /**
   * Creates a new AnimeAvro RecordBuilder.
   * @return A new AnimeAvro RecordBuilder
   */
  public static AnimeAvro.Builder newBuilder() {
    return new AnimeAvro.Builder();
  }

  /**
   * Creates a new AnimeAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AnimeAvro RecordBuilder
   */
  public static AnimeAvro.Builder newBuilder(AnimeAvro.Builder other) {
    if (other == null) {
      return new AnimeAvro.Builder();
    } else {
      return new AnimeAvro.Builder(other);
    }
  }

  /**
   * Creates a new AnimeAvro RecordBuilder by copying an existing AnimeAvro instance.
   * @param other The existing instance to copy.
   * @return A new AnimeAvro RecordBuilder
   */
  public static AnimeAvro.Builder newBuilder(AnimeAvro other) {
    if (other == null) {
      return new AnimeAvro.Builder();
    } else {
      return new AnimeAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for AnimeAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnimeAvro>
    implements org.apache.avro.data.RecordBuilder<AnimeAvro> {

    /** Title of the Anime */
    private java.lang.CharSequence title;
    /** Release Year of Anime */
    private long releaseYear;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AnimeAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.releaseYear)) {
        this.releaseYear = data().deepCopy(fields()[1].schema(), other.releaseYear);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AnimeAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(AnimeAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.releaseYear)) {
        this.releaseYear = data().deepCopy(fields()[1].schema(), other.releaseYear);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'title' field.
      * Title of the Anime
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * Title of the Anime
      * @param value The value of 'title'.
      * @return This builder.
      */
    public AnimeAvro.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.title = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * Title of the Anime
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'title' field.
      * Title of the Anime
      * @return This builder.
      */
    public AnimeAvro.Builder clearTitle() {
      title = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'releaseYear' field.
      * Release Year of Anime
      * @return The value.
      */
    public long getReleaseYear() {
      return releaseYear;
    }


    /**
      * Sets the value of the 'releaseYear' field.
      * Release Year of Anime
      * @param value The value of 'releaseYear'.
      * @return This builder.
      */
    public AnimeAvro.Builder setReleaseYear(long value) {
      validate(fields()[1], value);
      this.releaseYear = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'releaseYear' field has been set.
      * Release Year of Anime
      * @return True if the 'releaseYear' field has been set, false otherwise.
      */
    public boolean hasReleaseYear() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'releaseYear' field.
      * Release Year of Anime
      * @return This builder.
      */
    public AnimeAvro.Builder clearReleaseYear() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AnimeAvro build() {
      try {
        AnimeAvro record = new AnimeAvro();
        record.title = fieldSetFlags()[0] ? this.title : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.releaseYear = fieldSetFlags()[1] ? this.releaseYear : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AnimeAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<AnimeAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AnimeAvro>
    READER$ = (org.apache.avro.io.DatumReader<AnimeAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.title);

    out.writeLong(this.releaseYear);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.releaseYear = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 1:
          this.releaseYear = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










